# Site settings
title: Aniket kumar blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://007aniketkumar.github.io"
github_username:  007aniketkumar

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
